# Generated by Django 3.2.21 on 2023-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='short_description',
        ),
        migrations.AddField(
            model_name='note',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
